version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=production
      - APP_KEY=base64:...
      - DB_CONNECTION=sqlite
      # ...otras variables necesarias

  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./:/var/www


